name: Force Rebuild Dev Portal

on:
  workflow_dispatch:

jobs:
  rebuild-dev-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Dev Portal
        shell: bash
        run: |
          echo "Rebuilding all of dev-portal"
          curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
