# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Apply a product label based on the product selected in the issue template's
# product list.
#
# https://github.com/marketplace/actions/advanced-issue-labeler
# https://github.com/redhat-plumbers-in-action/advanced-issue-labeler
# https://github.com/redhat-plumbers-in-action/issue-forms-automation/blob/main/.github/workflows/issue-labeler.yml

# Inspired by: https://github.com/stefanbuck/ristorante
# See: https://stefanbuck.com/blog/codeless-contributions-with-github-issue-forms

name: Issue labeler
on:
  issues:
    types: [ opened, edited ]

jobs:
  label-issues-policy:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      matrix:
        template: [ docs.yml ]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@2ea9b35a8c584529ed00891a8f7e41dc46d0441e # v3.2.1
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Set labels based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@b80ae64e3e156e9c111b075bfa04b295d54e8e2e # v3.2.4
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
 
