name: Reload dev portal

on:
  workflow_call:
    inputs:
      base_sha:
        description: 'Base SHA for changed files comparison'
        required: true
        type: string
      head_sha:
        description: 'Head SHA for changed files comparison'
        required: true
        type: string
    secrets:
      dev-portal-deploy-hook-prod:
      revalidate-token:
      bot-bypass-token:

jobs:
  reload-dev-portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files in the content/ subdirectories
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
        with:
          files: |
            content/**
          base_sha: ${{ inputs.base_sha }}
          sha: ${{ inputs.head_sha }}
          json: true

      - name: Print changed files
        run: |
          echo "Changed files:"
          echo ${{ steps.changed-files.outputs.all_changed_files }} | xargs -n 1

      - name: Check for added or deleted files
        id: check-files
        run: |
          HAS_ADDED=$(echo ${{ steps.changed-files.outputs.added_files }} | grep . > /dev/null && echo 'true' || echo 'false')
          HAS_DELETED=$(echo ${{ steps.changed-files.outputs.deleted_files }} | grep . > /dev/null && echo 'true' || echo 'false')
          echo "has_added=$HAS_ADDED" >> $GITHUB_OUTPUT
          echo "has_deleted=$HAS_DELETED" >> $GITHUB_OUTPUT

      - name: Redeploy if files added/deleted or >= 50
        if: steps.check-files.outputs.has_added == 'true' || steps.check-files.outputs.has_deleted == 'true' || steps.changed-files.outputs.all_changed_files_count >= 50
        run: |
          echo "File added/deleted or >= 50, redeploying dev-portal"
          curl -X POST ${{ secrets.dev-portal-deploy-hook-prod }}

      - name: Map files to URLs
        id: map-files
        if: steps.changed-files.outputs.all_changed_files_count < 50
        run: |
          FILES_URLS=$(node ./scripts/map-files-to-urls.mjs ${{ steps.changed-files.outputs.all_changed_files }})
          echo "FILES_URLS=$FILES_URLS" >> $GITHUB_OUTPUT

      - name: Print urls
        if: steps.changed-files.outputs.all_changed_files_count < 50
        run: echo ${{ steps.map-files.outputs.FILES_URLS }} | xargs -n 1

      - name: Revalidate paths
        if: steps.changed-files.outputs.all_changed_files_count < 50
        id: revalidate-paths
        env:
          url: 'https://developer.hashicorp.com/api/revalidate/paths'
          auth: 'Authorization: Bearer ${{ secrets.revalidate-token }}'
          bot-bypass: '${{ secrets.bot-bypass-token }}'
        run: |
          curl -X POST "${{ env.url }}" \
            -H "${{ env.auth }}" \
            -H "Content-Type: application/json" \
            -H "X-BOT-BYPASS: ${{ env.bot-bypass }}" \
            -d '{"paths": ${{ steps.map-files.outputs.FILES_URLS }} }'
